apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: publication-mapper-db-pv-claim
  labels:
    app: publication-mapper

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
