default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: pubmap_dev
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: pubmap_test
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  database: pubmap_prod
  url: <%= ENV['DATABASE_URL'] %>
